import type { Metadata } from "next";
import { PT_Serif } from "next/font/google"; // Import PT_Serif
import "./globals.css";

// Configure PT_Serif font with all weights and styles
const ptSerif = PT_Serif({
  weight: ["400", "700"], // Regular and Bold weights
  style: ["normal", "italic"], // Normal and Italic styles
  subsets: ["latin"],
  variable: "--font-pt-serif", // Define a CSS variable for the font
});

export const metadata: Metadata = {
  title: "STDMDC",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ptSerif.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}